// generated by go generate; DO NOT EDIT.

package main

// This data is derived from files in the font/fixed directory of the Plan 9
// Port source code (https://github.com/9fans/plan9port) which were originally
// based on the public domain X11 misc-fixed font files.

import (
	"image"
	"image/color"
	"image/draw"

	"periph.io/x/periph/experimental/devices/ssd1327/image4bit"
)

type bit bool

func (b bit) RGBA() (uint32, uint32, uint32, uint32) {
	if b {
		return 65535, 65535, 65535, 65535
	}
	return 0, 0, 0, 0
}

func convertBit(c color.Color) color.Color {
	r, g, b, _ := c.RGBA()
	return bit((r | g | b) >= 0x8000)
}

type alpha struct {
	image4bit.VerticalLSB
}

func (a *alpha) ColorModel() color.Model {
	return color.ModelFunc(convertBit)
}

func (a *alpha) At(x, y int) color.Color {
	return convertBit(a.VerticalLSB.At(x, y))
}

// glyphs contains chars 0x21 to 0x7F.
var glyphs = []alpha{
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 0, 0, 0, 240, 0, 0, 0, 0, 0, 255, 0, 0, 0, 0, 0, 255, 0, 0, 0, 0, 0, 255, 0, 0, 0, 0, 0, 240, 0, 0, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 0, 0, 240, 0, 240, 0, 0, 0, 255, 0, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255, 0, 255, 0, 0, 15, 255, 15, 255, 15, 0, 15, 255, 15, 255, 15, 0, 0, 15, 0, 15, 0, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 240, 255, 240, 240, 0, 15, 240, 255, 240, 0, 0, 240, 240, 255, 240, 15, 0, 0, 0, 15, 0, 0, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 0, 240, 0, 0, 0, 240, 15, 240, 15, 0, 240, 15, 0, 0, 0, 255, 0, 0, 0, 240, 15, 0, 240, 0, 255, 0, 0, 15, 240, 15, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 240, 240, 0, 0, 0, 255, 0, 0, 255, 0, 0, 240, 15, 15, 240, 0, 240, 15, 240, 240, 240, 15, 240, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 0, 0, 0, 240, 0, 0, 0, 0, 0, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 240, 0, 0, 0, 0, 255, 0, 0, 0, 0, 255, 0, 0, 0, 0, 0, 15, 240, 0, 0, 0, 0, 0, 15, 240, 0, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 0, 0, 240, 0, 0, 0, 0, 0, 0, 255, 0, 0, 0, 0, 0, 0, 255, 0, 0, 0, 0, 240, 15, 0, 0, 0, 240, 15, 0, 0, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 240, 0, 0, 240, 0, 240, 240, 255, 255, 240, 240, 0, 240, 15, 15, 240, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 240, 0, 0, 0, 240, 240, 255, 240, 240, 0, 0, 0, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255, 255, 15, 0, 0, 15, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 240, 240, 240, 240, 240, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 240, 255, 240, 0, 0, 0, 0, 15, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 240, 0, 0, 0, 0, 240, 15, 0, 0, 0, 240, 15, 0, 0, 0, 255, 0, 0, 0, 0, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 0, 0, 240, 240, 0, 0, 240, 15, 0, 0, 15, 240, 255, 0, 0, 0, 0, 255, 255, 0, 0, 0, 0, 255, 0, 15, 240, 240, 15, 0, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 0, 0, 0, 240, 0, 0, 0, 240, 15, 255, 0, 0, 0, 0, 0, 255, 0, 0, 0, 0, 0, 255, 0, 0, 0, 240, 240, 255, 240, 240, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 0, 240, 240, 240, 240, 0, 255, 0, 0, 0, 0, 255, 0, 0, 0, 0, 240, 15, 0, 240, 15, 15, 0, 0, 255, 240, 240, 240, 240, 240, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 240, 240, 240, 240, 240, 240, 0, 0, 0, 0, 240, 15, 0, 0, 240, 255, 240, 0, 0, 0, 0, 0, 0, 255, 15, 240, 240, 240, 240, 15, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 240, 0, 0, 0, 240, 15, 255, 0, 240, 15, 0, 0, 255, 0, 255, 240, 240, 240, 255, 240, 0, 0, 0, 0, 255, 0, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 240, 240, 240, 240, 240, 240, 255, 0, 0, 0, 0, 0, 255, 240, 15, 15, 15, 240, 0, 0, 0, 0, 0, 255, 15, 240, 240, 240, 240, 15, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 0, 0, 240, 240, 240, 0, 240, 15, 0, 0, 0, 0, 255, 0, 240, 240, 240, 0, 255, 15, 0, 0, 0, 255, 15, 240, 240, 240, 240, 15, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 240, 240, 240, 240, 240, 240, 0, 0, 0, 0, 240, 15, 0, 0, 0, 255, 0, 0, 0, 0, 255, 0, 0, 0, 0, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 0, 240, 240, 240, 240, 0, 255, 0, 0, 0, 0, 255, 15, 240, 240, 240, 240, 15, 255, 0, 0, 0, 0, 255, 15, 240, 240, 240, 240, 15, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 0, 240, 240, 240, 240, 0, 255, 0, 0, 0, 0, 255, 15, 240, 240, 240, 15, 255, 0, 0, 0, 0, 0, 255, 0, 240, 240, 240, 15, 0, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 240, 0, 0, 0, 0, 15, 255, 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 240, 255, 240, 0, 0, 0, 0, 15, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 240, 0, 0, 0, 0, 15, 255, 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255, 255, 15, 0, 0, 15, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 240, 0, 0, 0, 240, 15, 0, 0, 240, 15, 0, 0, 0, 0, 0, 15, 240, 0, 0, 0, 0, 0, 0, 15, 240, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15, 15, 15, 15, 15, 15, 240, 240, 240, 240, 240, 240, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 0, 240, 0, 0, 0, 0, 0, 0, 15, 240, 0, 0, 0, 0, 0, 0, 15, 240, 0, 0, 0, 240, 15, 0, 0, 240, 15, 0, 0, 0, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 0, 240, 240, 240, 240, 0, 255, 0, 0, 0, 0, 255, 0, 0, 0, 0, 240, 15, 0, 0, 0, 255, 0, 0, 0, 0, 0, 240, 0, 0, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 0, 240, 240, 240, 240, 0, 255, 0, 0, 0, 0, 255, 255, 0, 240, 15, 15, 255, 255, 0, 15, 240, 15, 255, 15, 240, 240, 240, 240, 0, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 0, 0, 240, 240, 0, 0, 240, 15, 0, 0, 15, 240, 255, 0, 0, 0, 0, 255, 255, 15, 15, 15, 15, 255, 255, 0, 0, 0, 0, 255, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 240, 240, 240, 240, 240, 0, 0, 255, 0, 0, 0, 255, 0, 255, 240, 240, 240, 15, 0, 255, 0, 0, 0, 255, 240, 255, 240, 240, 240, 15, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 0, 240, 240, 240, 240, 0, 255, 0, 0, 0, 0, 15, 255, 0, 0, 0, 0, 0, 255, 0, 0, 0, 0, 0, 15, 240, 240, 240, 240, 15, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 240, 240, 240, 240, 240, 0, 0, 255, 0, 0, 0, 255, 0, 255, 0, 0, 0, 255, 0, 255, 0, 0, 0, 255, 240, 255, 240, 240, 240, 15, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 240, 240, 240, 240, 240, 240, 255, 0, 0, 0, 0, 0, 255, 240, 240, 240, 0, 0, 255, 0, 0, 0, 0, 0, 255, 240, 240, 240, 240, 240, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 240, 240, 240, 240, 240, 240, 255, 0, 0, 0, 0, 0, 255, 240, 240, 240, 0, 0, 255, 0, 0, 0, 0, 0, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 0, 240, 240, 240, 240, 0, 255, 0, 0, 0, 0, 15, 255, 0, 0, 0, 0, 0, 255, 0, 0, 15, 15, 255, 15, 240, 240, 240, 15, 255, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 240, 0, 0, 0, 0, 240, 255, 0, 0, 0, 0, 255, 255, 240, 240, 240, 240, 255, 255, 0, 0, 0, 0, 255, 255, 0, 0, 0, 0, 255, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 0, 240, 240, 240, 240, 240, 0, 0, 0, 255, 0, 0, 0, 0, 0, 255, 0, 0, 0, 0, 0, 255, 0, 0, 0, 240, 240, 255, 240, 240, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 0, 0, 0, 240, 240, 240, 0, 0, 0, 0, 255, 0, 0, 0, 0, 0, 255, 0, 0, 0, 0, 0, 255, 0, 15, 240, 240, 240, 15, 0, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 240, 0, 0, 0, 0, 240, 255, 0, 0, 240, 15, 0, 255, 240, 15, 0, 0, 0, 255, 0, 15, 240, 0, 0, 255, 0, 0, 0, 15, 240, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 240, 0, 0, 0, 0, 0, 255, 0, 0, 0, 0, 0, 255, 0, 0, 0, 0, 0, 255, 0, 0, 0, 0, 0, 255, 240, 240, 240, 240, 240, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 240, 0, 0, 0, 0, 240, 255, 255, 0, 0, 255, 255, 255, 0, 255, 255, 0, 255, 255, 0, 0, 0, 0, 255, 255, 0, 0, 0, 0, 255, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 240, 0, 0, 0, 0, 240, 255, 240, 0, 0, 0, 255, 255, 0, 15, 240, 0, 255, 255, 0, 0, 0, 15, 255, 255, 0, 0, 0, 0, 255, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 0, 240, 240, 240, 240, 0, 255, 0, 0, 0, 0, 255, 255, 0, 0, 0, 0, 255, 255, 0, 0, 0, 0, 255, 15, 240, 240, 240, 240, 15, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 240, 240, 240, 240, 240, 0, 255, 0, 0, 0, 0, 255, 255, 240, 240, 240, 240, 15, 255, 0, 0, 0, 0, 0, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 0, 240, 240, 240, 240, 0, 255, 0, 0, 0, 0, 255, 255, 0, 0, 0, 0, 255, 255, 0, 240, 0, 0, 255, 15, 240, 240, 255, 240, 15, 0, 0, 0, 0, 0, 15},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 240, 240, 240, 240, 240, 0, 255, 0, 0, 0, 0, 255, 255, 240, 240, 240, 240, 15, 255, 0, 15, 240, 0, 0, 255, 0, 0, 0, 15, 240, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 0, 240, 240, 240, 240, 0, 255, 0, 0, 0, 0, 15, 15, 240, 240, 240, 240, 0, 0, 0, 0, 0, 0, 255, 15, 240, 240, 240, 240, 15, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 0, 240, 240, 240, 240, 240, 0, 0, 0, 255, 0, 0, 0, 0, 0, 255, 0, 0, 0, 0, 0, 255, 0, 0, 0, 0, 0, 255, 0, 0, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 240, 0, 0, 0, 0, 240, 255, 0, 0, 0, 0, 255, 255, 0, 0, 0, 0, 255, 255, 0, 0, 0, 0, 255, 15, 240, 240, 240, 240, 15, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 240, 0, 0, 0, 0, 240, 255, 0, 0, 0, 0, 255, 0, 255, 0, 0, 255, 0, 0, 15, 240, 240, 15, 0, 0, 0, 255, 255, 0, 0, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 240, 0, 0, 0, 0, 240, 255, 0, 0, 0, 0, 255, 255, 0, 240, 240, 0, 255, 255, 240, 15, 15, 240, 255, 255, 15, 0, 0, 15, 255, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 240, 0, 0, 0, 0, 240, 15, 240, 0, 0, 240, 15, 0, 15, 240, 240, 15, 0, 0, 255, 0, 0, 255, 0, 255, 0, 0, 0, 0, 255, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 0, 240, 0, 0, 0, 240, 0, 15, 240, 0, 240, 15, 0, 0, 15, 240, 15, 0, 0, 0, 0, 255, 0, 0, 0, 0, 0, 255, 0, 0, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 240, 240, 240, 240, 240, 240, 0, 0, 0, 0, 240, 15, 0, 0, 240, 255, 0, 0, 0, 240, 15, 0, 0, 0, 255, 240, 240, 240, 240, 240, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 0, 255, 15, 15, 15, 0, 0, 255, 0, 0, 0, 0, 0, 255, 0, 0, 0, 0, 0, 255, 0, 0, 0, 0, 0, 255, 0, 0, 0, 0, 0, 15, 15, 15, 15, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 0, 240, 0, 0, 0, 0, 0, 15, 240, 0, 0, 0, 0, 0, 15, 240, 0, 0, 0, 0, 0, 0, 255, 0, 0, 0, 0, 0, 0, 255, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 0, 15, 15, 15, 255, 0, 0, 0, 0, 0, 255, 0, 0, 0, 0, 0, 255, 0, 0, 0, 0, 0, 255, 0, 0, 0, 0, 0, 255, 0, 0, 15, 15, 15, 15, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 0, 0, 0, 240, 0, 0, 0, 240, 15, 0, 15, 240, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15, 15, 15, 15, 15, 15},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 0, 0, 15, 240, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15, 15, 15, 15, 240, 240, 15, 15, 15, 15, 255, 15, 240, 240, 240, 15, 255, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 240, 0, 0, 0, 0, 0, 255, 0, 0, 0, 0, 0, 255, 240, 15, 15, 15, 240, 255, 0, 0, 0, 0, 255, 255, 15, 240, 240, 240, 15, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 240, 15, 15, 15, 15, 240, 255, 0, 0, 0, 0, 0, 15, 240, 240, 240, 240, 15, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 240, 0, 0, 0, 0, 0, 255, 240, 15, 15, 15, 240, 255, 255, 0, 0, 0, 0, 255, 15, 240, 240, 240, 15, 255, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 240, 15, 15, 15, 15, 240, 255, 15, 15, 15, 15, 15, 15, 240, 240, 240, 240, 15, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 0, 0, 240, 240, 240, 0, 0, 255, 0, 0, 0, 15, 240, 255, 240, 240, 0, 0, 0, 255, 0, 0, 0, 0, 0, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 240, 15, 15, 15, 240, 15, 15, 240, 240, 240, 15, 0, 15, 240, 240, 240, 240, 0, 15, 0, 0, 0, 0, 15},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 240, 0, 0, 0, 0, 0, 255, 0, 0, 0, 0, 0, 255, 240, 15, 15, 15, 240, 255, 0, 0, 0, 0, 255, 255, 0, 0, 0, 0, 255, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15, 0, 0, 0, 0, 15, 255, 0, 0, 0, 0, 0, 255, 0, 0, 0, 240, 240, 255, 240, 240, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15, 0, 0, 0, 0, 15, 255, 0, 0, 0, 0, 0, 255, 0, 240, 0, 0, 0, 255, 0, 15, 0, 0, 0, 15},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 240, 0, 0, 0, 0, 0, 255, 0, 0, 0, 0, 0, 255, 0, 0, 240, 15, 0, 255, 15, 15, 240, 0, 0, 255, 0, 0, 0, 15, 240, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 0, 0, 240, 240, 0, 0, 0, 0, 0, 255, 0, 0, 0, 0, 0, 255, 0, 0, 0, 0, 0, 255, 0, 0, 0, 240, 240, 255, 240, 240, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255, 15, 240, 15, 240, 0, 255, 0, 255, 0, 255, 0, 255, 0, 15, 0, 255, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255, 240, 15, 15, 15, 240, 255, 0, 0, 0, 0, 255, 255, 0, 0, 0, 0, 255, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 240, 15, 15, 15, 15, 240, 255, 0, 0, 0, 0, 255, 15, 240, 240, 240, 240, 15, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255, 240, 15, 15, 15, 240, 255, 240, 0, 0, 0, 255, 255, 0, 15, 15, 15, 0, 15, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 240, 15, 15, 15, 240, 255, 255, 0, 0, 0, 240, 255, 0, 15, 15, 15, 0, 255, 0, 0, 0, 0, 0, 15},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15, 240, 15, 15, 15, 240, 0, 255, 0, 0, 0, 0, 0, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 240, 15, 15, 15, 15, 240, 0, 15, 15, 240, 240, 0, 15, 240, 240, 240, 240, 15, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255, 0, 0, 0, 0, 15, 255, 15, 15, 0, 0, 0, 255, 0, 0, 0, 0, 0, 15, 240, 240, 240, 15, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255, 0, 0, 0, 0, 255, 255, 0, 0, 0, 0, 255, 15, 240, 240, 240, 15, 255, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255, 0, 0, 0, 255, 0, 15, 240, 0, 240, 15, 0, 0, 15, 240, 15, 0, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255, 0, 0, 0, 255, 0, 255, 0, 255, 0, 255, 0, 15, 240, 15, 240, 15, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15, 240, 0, 0, 240, 15, 0, 0, 255, 255, 0, 0, 240, 15, 0, 0, 15, 240, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255, 0, 0, 0, 0, 255, 255, 0, 0, 0, 240, 255, 0, 15, 15, 15, 0, 255, 15, 0, 0, 0, 0, 15},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15, 15, 15, 15, 255, 15, 0, 0, 240, 15, 0, 0, 240, 255, 240, 240, 240, 240, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 0, 0, 240, 15, 15, 15, 0, 0, 255, 0, 0, 0, 0, 240, 240, 15, 0, 0, 0, 0, 240, 15, 0, 0, 0, 0, 255, 0, 0, 0, 0, 0, 0, 15, 15, 15},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 0, 0, 0, 240, 0, 0, 0, 0, 0, 255, 0, 0, 0, 0, 0, 255, 0, 0, 0, 0, 0, 255, 0, 0, 0, 0, 0, 255, 0, 0, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 0, 15, 15, 15, 240, 0, 0, 0, 0, 0, 255, 0, 0, 0, 0, 15, 240, 240, 0, 0, 0, 15, 240, 0, 0, 0, 0, 0, 255, 0, 0, 15, 15, 15, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 0, 0, 240, 0, 0, 240, 0, 255, 0, 15, 240, 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
	{
		image4bit.VerticalLSB{
			Pix:    []byte{0, 0, 0, 0, 0, 0, 0, 0, 240, 240, 240, 0, 0, 255, 15, 240, 15, 255, 0, 255, 255, 15, 240, 255, 0, 255, 255, 240, 255, 255, 0, 15, 255, 240, 255, 15, 0, 0, 0, 0, 0, 0},
			Stride: 6,
			Rect:   image.Rectangle{Max: image.Point{6, 13}},
		},
	},
}

// drawText draws text on an image.
//
// It is intentionally very limited. Use golang.org/x/image/font for complete
// functionality.
func drawText(dst draw.Image, p image.Point, t string) {
	const base = 0x21
	r := image.Rect(0, 0, 7, 13).Add(p)
	u := image.Uniform{C: image4bit.Gray4(15)}
	for _, c := range t {
		if c >= base && int(c-base) < len(glyphs) {
			draw.DrawMask(dst, r, &u, image.Point{}, &glyphs[c-base], image.Point{}, draw.Over)
		}
		r = r.Add(image.Point{7, 0})
	}
}
